### ISSUE TITLE
undefined method `call' for "result == false":String

### ISSUE THREAD

**Issue by Rui90** [evinsou/paperclip-googledrive#21]
I am kinda running in circles around here. I had this gem:

gem "paperclip", git: "git://github.com/thoughtbot/paperclip.git"

But when I added gem 'paperclip-googledrive' I got an error: paperclip-googledrive (>= 0) ruby depends on paperclip (~> 3.4) ruby

I solved this error by removing the git part from paperclip gem and making a new bundle install with gem "paperclip" only, but now after following paperclip-googledrive tutorial on create method I have got this error:

```
NoMethodError in VideosController#create 
undefined method `call' for "result == false":String
```

I've been reading around the internet that is may be due to incompatibilies with that paperclip version and rails 4.2.4 so it can be a really big problem. Anyone know how to fix this?

This is my model btw:

```
class Video < ActiveRecord::Base
  belongs_to :channel
  has_many :video_tags
  letsrate_rateable "rate_video"
  has_attached_file :videofile, styles: {
      :medium => {
          :geometry => "640x480",
          :format => 'mp4'
      },
      :thumb => { :geometry => "160x120", :format => 'jpeg', :time => 10}
  }, :processors => [:transcoder], :storage => :google_drive, :google_drive_credentials => "#{Rails.root}/config/google_drive.yml"

  validates_attachment_content_type :videofile, content_type: /\Avideo\/.*\Z/
```

**Comment by AmineBahmed** [comment]
yes it seems that the paperclip 3.4 is incompatible with rails 4.2, so you can use paperclip-googledrive-new which work with paperclip 5.0.0
`gem 'paperclip-googledrive-new'`
